### ISSUE TITLE
TypeError: Cannot read property 'delete' of undefined

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/discv5#150]
Found so many errors like this

```
Nov-10 02:21:57.556 [API]             error: uncaughtException: Cannot read property 'delete' of undefined
TypeError: Cannot read property 'delete' of undefined
    at Map.removeVote [as onTimeout] (/usr/app/node_modules/@chainsafe/discv5/lib/service/addrVotes.js:24:24)
    at Timeout.<anonymous> (/usr/app/node_modules/@chainsafe/discv5/lib/util/timeoutMap.js:25:22)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) message=Cannot read property 'delete' of undefined
```

currently lodestar uses discv 0.6.4, not sure if it happens in 0.6.5

**Comment by tuyennhv** [comment]
0.6.5 correct the callback by calling `removeTally()` instead of `removeVote()` on the timed out map so should not be an issue
